apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: quark 
  janus-idp.io/tekton: quark
  backstage.io/kubernetes-id: quark
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: quark
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  