apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: quark
  janus-idp.io/tekton: quark
  backstage.io/kubernetes-id: quark
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: quark
resources: 
- deployment.yaml
- route.yaml
- service.yaml
