apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: quark
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quark 
  name: quark
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: quark 
